### PR TITLE
Add VSIX manifest identity version

### PR DESCRIPTION
**Pull request by Plac3hold3r**
* Support for version in VSIX schema v1 [Link](https://msdn.microsoft.com/en-us/library/ee191547.aspx#Anchor_0)
* Support for version in VSIX schema v2 [Link](https://docs.microsoft.com/en-us/visualstudio/extensibility/vsix-extension-schema-2-0-reference#metadata-element)

* Fix spelling on VB "Vsix.Description" assembly attribute

### CODE REVIEW

**Comment by kzu** [comment]
Thanks a lot for your contribution @Plac3hold3r! 

I should point out that for VSIX version, a most common case is to actually use MSBuild expansions there, like `Version="|MyProject.Vsix;GetVsixVersion|"`. Have you checked that this will still render the right value in that case too?

Thanks again

**Comment by Plac3hold3r** [comment]
Ah, I see what you are saying. Projects like [Microsoft nodejstools](https://github.com/Microsoft/nodejstools/blob/master/Nodejs/Product/Nodejs/source.extension.vsixmanifest#L3) and [Microsoft  xamarin-android](https://github.com/xamarin/xamarin-android/blob/master/build-tools/create-vsix/source.extension.vsixmanifest#L4) all use a variation of the pattern you describe were MSBuild is used to add the version number. I was not aware of this pattern, which is pretty cool.

I tested it out and you are correct it does not render the correct version number but rather the string. A side note, a copy of the correct manifest with the correct version number is generated and placed in the output directory. But I'm not sure if there is support currently for changing to look at that version of the outputted file or the viability of doing so?

For reference, [this](https://github.com/Plac3hold3r/MvxScaffolding/tree/master/src/MvxScaffolding.Vsix/Targets) was the project with the use case. I'm using the version number in the manifest with a modified version of MSBuilder to include the version programmatically to make it accessible within the VSIX wizard. This has been working fine for my current use case, but I see your point that it is probably not well suited for current practices in terms of how version numbering is defined within MSBuild.

**Comment by Plac3hold3r** [comment]
I have updated the PR to now use the `IntermediateVsixManifest` as suggested. I'm was only able to test with Visual Studio 2017 15.6.6., which worked without issue in parsing the version number correctly from the version defined in my csproj and `|%CurrentProject%;GetVsixVersion|` in my VSIX manifest.

**Comment by kzu** [comment]
Great, thanks for your contribution!

**Pull request merged**
