### PR TITLE
Set DevelopmentDepencency true for GenerateAssemblyInfo

### PR DESCRIPTION
**Pull request by AroglDarthu**
Perhaps this also solves issue #22 , can't say for sure because the issue does not mention the package.

### CODE REVIEW

**Comment by AroglDarthu** [comment]
I don't understand how the version in the nuspec file (0.2.0) can be lower than the published version (0.2.1). I've updated to 0.2.2 now.

**Comment by kzu** [comment]
Thanks for the PR!

**Comment by AroglDarthu** [comment]
@kzu 
NuGet.org still shows 0.2.1 as the latest version. Did I miss anything, or is there a manual step involved?

**Comment by kzu** [comment]
pushed the update

**Pull request merged**
